import React from 'react'
import Head from 'next/Head'

export default function Layout({title, children}) {
    return (
        <div>
        <Head>
          <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="container mx-auto max-w-5xl bg-red-300">
            {children}
        </main>
        </div>
    )
}
